services:
  nexus:
    image: sonatype/nexus3:3.68.1-java11       
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
      - "8123:8123"
    restart: always
 
volumes:
  nexus_data:


    