---
- name: Configurar servidor de banco de dados
  hosts: db01
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "mysecret"
  tasks:
    - name: Configurar hosts ansible
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items:
        - 192.168.56.3 control-node
        - 192.168.56.4 app01
        - 192.168.56.5 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql